---
version: 1
disable_existing_loggers: False
formatters:
    default:
        format: "%(asctime)s|%(module)s|%(levelname)s|%(message)s"

handlers:
    console:
        class: utils.TqdmLoggingHandler
        level: DEBUG
        formatter: default

root:
    level: INFO
    handlers: 
      - console
...