language: python
python:
  - "3.6"

install:
  - pip install -r requirements.txt
  - pip install https://download.pytorch.org/whl/cpu/torch-1.0.1.post2-cp36-cp36m-linux_x86_64.whl

script:
  - black --check --diff zarya tests
  - python3 -m pytest tests -x -v
